version: '3.7'

services:
  postgres:
    image: postgres:10.4-alpine
    env_file: ./.docker-env
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data_backups:/backups

  django:
    init: true
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    depends_on:
      - postgres
    env_file: ./.docker-env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t    

  jupyter:
    init: true
    build:
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    depends_on:
      - postgres
    env_file: ./.docker-env
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t 
