# Generated by Django 2.1.15 on 2020-11-08 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('slug', models.SlugField(help_text='A label for SEO', max_length=63)),
                ('text', models.TextField()),
                ('publish_date', models.DateField(default=datetime.date.today, verbose_name='date published')),
            ],
            options={
                'verbose_name': 'blog post',
                'ordering': ['-publish_date', 'title'],
                'get_latest_by': 'publish_date',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('slug', models.SlugField(help_text='An identifier', max_length=63)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='blog_categories', to='blog.Category'),
        ),
    ]
